server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parcinfo-db?createDatabseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true
    password: user
    username: user
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: spring_parcinfo


  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true